[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[phases.setup]
cmds = ["echo 'Using Dockerfile for deployment'"]